#pragma once
#ifndef EONSIMULATOR_EVENTCALLSERVICETERMINATION_H
#define EONSIMULATOR_EVENTCALLSERVICETERMINATION_H

class EventCallServiceTermination {

};

#endif //EONSIMULATOR_EVENTCALLSERVICETERMINATION_H